scrape_configs:
  - job_name: BK-prod-front-1
    scrape_interval: 5s
    static_configs:
    - targets: ['95.216.210.66:9100']

  - job_name: BK-stage
    scrape_interval: 5s
    static_configs:
    - targets: ['88.198.55.137:9100']

  - job_name: BK-app-prod
    scrape_interval: 5s
    static_configs:
    - targets: ['65.108.247.119:9100']

  - job_name: BK-gw-prod
    scrape_interval: 5s
    static_configs:
    - targets: ['65.108.150.186:9100']

  - job_name: BK-parser-prod
    scrape_interval: 5s
    static_configs:
    - targets: ['65.108.58.170:9100']

  - job_name: BK-bkp
    scrape_interval: 5s
    static_configs:
    - targets: ['142.132.229.99:9100']

  - job_name: BK-monitoring-log
    scrape_interval: 5s
    static_configs:
    - targets: ['65.108.56.221:9100']

  - job_name: BK-app-qa
    scrape_interval: 5s
    static_configs:
    - targets: ['168.119.51.221:9100']

  - job_name: BK-gw-qa
    scrape_interval: 5s
    static_configs:
    - targets: ['168.119.154.105:9100']

  - job_name: BK-parser-qa
    scrape_interval: 5s
    static_configs:
    - targets: ['168.119.52.253:9100']

  - job_name: BK-dev
    scrape_interval: 5s
    static_configs:
    - targets: ['65.108.147.114:9100']  

  - job_name: loldev
    scrape_interval: 5s
    static_configs:
    - targets: ['95.217.119.210:9100']

  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - https://betunlim.com/live
        - https://betunlim.com/live/11
        - https://stage.bet-unlim.com/live/
        - https://stage.bet-unlim.com/live/11
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115

rule_files:
  - 'alert.rules'

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"
